version: "3"
services:
  kafka:
    image: local/kafka:latest
    command: bin/kafka-server-start.sh config/server.properties --override zookeeper.connect=zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - kafka_net

  cmak:
    image: local/cmak:latest
    command: bin/cmak
    environment: 
      ZK_HOSTS: "zookeeper:2181"
    ports:
      - "9000:9000"
    networks:
      - kafka_net

  zookeeper:
    image: local/kafka:latest
    command: bin/zookeeper-server-start.sh config/zookeeper.properties
    expose:
      - "2181"
    networks:
      - kafka_net

networks:
  kafka_net:
    driver: bridge